version: '3'
services:


  db:
    image: postgres
    volumes:
      - ./project/tmp/db:/var/lib/postgresql/data
    container_name: little_blog_db
    ports:
      - "5432:5432"


  web:
    build: .
    image: little_blog_app_image:latest
    # command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    working_dir: /project
    volumes:
      - ./project:/project
    ports:
      - "3000:3000"
    depends_on:
      - db
    container_name: little_blog_web

